# Generated by Django 6.0.7 on 2026-08-18 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final_app', '0003_cart_order_product_orderitem_cartitem'),
        ('final_app', '0004_update_categories'),
    ]

    operations = [
    ]
